"""Safe SSH command execution with host-alias validation and output truncation.

All subprocess calls use argument arrays (no ``shell=True``).  Output is
truncated to a configurable maximum length.  Host aliases are validated to
prevent command injection.  Remote commands must be fixed strings generated
by system code, not user input.
"""

from __future__ import annotations

import contextlib
import logging
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

from fluid_scientist.execution.ssh import ProcessResult
from fluid_scientist.workstations.models import KnownHostStatus

logger = logging.getLogger(__name__)

_SAFE_HOST_ALIAS = re.compile(r"^[A-Za-z0-9_.-]{1,128}$")

_DEFAULT_MAX_OUTPUT_CHARS = 10_000
_DEFAULT_TIMEOUT = 30.0
_KEYSCAN_TIMEOUT = 15.0
_KEYGEN_TIMEOUT = 10.0

# SSH standard private key names that the client auto-discovers.
# When -i is used, SSH replaces its default list, so these must be
# included explicitly in the -i arguments.
_STANDARD_KEY_NAMES = frozenset({
    "id_rsa", "id_ecdsa", "id_ed25519", "id_xmss", "id_dsa", "identity",
})

# Suffixes that identify private key files (e.g. fluid_scientist_ed25519).
_KEY_SUFFIXES = ("_rsa", "_ed25519", "_ecdsa", "_dsa")

# Maximum number of identity files to try (prevents MaxAuthTries exhaustion).
_MAX_IDENTITY_FILES = 5

# Files to exclude when scanning ~/.ssh/ for private keys.
_SSH_DIR_EXCLUDES = frozenset({
    "known_hosts", "known_hosts2", "config", "authorized_keys",
    "authorized_keys2", "environment",
})

# Extensions to exclude (scripts, public keys, etc.).
_SSH_DIR_EXCLUDE_SUFFIXES = (".pub", ".ps1", ".sh", ".py", ".bat", ".cmd", ".pem", ".crt")


@dataclass(frozen=True)
class SafeHostAlias:
    """Validated SSH host alias that prevents command injection.

    Only ``[A-Za-z0-9_.-]`` characters are allowed, with a length of 1-128.
    """

    value: str

    def __post_init__(self) -> None:
        if not _SAFE_HOST_ALIAS.fullmatch(self.value):
            raise ValueError("host alias must contain only [A-Za-z0-9_.-] and be 1-128 characters")

    def __str__(self) -> str:
        return self.value


class CommandRunner(Protocol):
    """Protocol for executing subprocess commands safely."""

    def run(
        self,
        argv: tuple[str, ...],
        *,
        timeout: float,
        input_text: str | None = None,
    ) -> ProcessResult: ...


class SubprocessCommandRunner:
    """Default :class:`CommandRunner` backed by :func:`subprocess.run`.

    Never uses ``shell=True``; always passes an explicit argument array.
    """

    def run(
        self,
        argv: tuple[str, ...],
        *,
        timeout: float,
        input_text: str | None = None,
    ) -> ProcessResult:
        completed = subprocess.run(
            argv,
            capture_output=True,
            text=True,
            timeout=timeout,
            input=input_text,
            check=False,
        )
        return ProcessResult(
            completed.returncode,
            completed.stdout,
            completed.stderr,
        )


class SSHCommandRunner:
    """Encapsulates system SSH calls with strict safety constraints.

    - All subprocess calls use argument arrays (no ``shell=True``).
    - Output is truncated to *max_output_chars* (default 10 000).
    - Host aliases are validated via :class:`SafeHostAlias`.
    - Remote commands must be fixed strings generated by system code.
    - Logs are sanitised: no private keys, passwords, or identity-file paths.
    """

    def __init__(
        self,
        *,
        runner: CommandRunner | None = None,
        default_timeout: float = _DEFAULT_TIMEOUT,
        max_output_chars: int = _DEFAULT_MAX_OUTPUT_CHARS,
        known_hosts_file: Path | None = None,
    ) -> None:
        self._runner = runner or SubprocessCommandRunner()
        self._default_timeout = default_timeout
        self._max_output_chars = max_output_chars
        self._known_hosts_file = known_hosts_file or (Path.home() / ".ssh" / "known_hosts")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def check_ssh_installed(self) -> bool:
        """Return ``True`` if the ``ssh`` binary is available on the system."""
        try:
            result = self._run(("ssh", "-V"), timeout=_KEYGEN_TIMEOUT)
        except OSError:
            return False
        except subprocess.TimeoutExpired:
            return False
        return result.returncode == 0

    def resolve_host(self, host_alias: str) -> dict:
        """Resolve SSH connection parameters for *host_alias* via ``ssh -G``.

        Returns a dict with keys ``hostname``, ``user``, ``port``,
        ``proxyjump``, and ``identityagent``.  Identity-file paths and
        other sensitive fields are deliberately excluded.
        """
        alias = SafeHostAlias(host_alias)
        logger.debug("resolving host parameters for %s", alias)
        try:
            result = self._run(
                ("ssh", "-G", str(alias)),
                timeout=self._default_timeout,
            )
        except OSError:
            logger.debug("ssh -G could not be started for %s", alias)
            return {}
        except subprocess.TimeoutExpired:
            logger.debug("ssh -G timed out for %s", alias)
            return {}
        if result.returncode != 0:
            logger.debug("ssh -G returned %d for %s", result.returncode, alias)
            return {}

        parsed: dict[str, object] = {}
        for line in result.stdout.splitlines():
            stripped = line.strip()
            if not stripped:
                continue
            parts = stripped.split(None, 1)
            if len(parts) != 2:
                continue
            key = parts[0].lower()
            value = parts[1]
            if key == "hostname":
                parsed["hostname"] = value
            elif key == "user":
                parsed["user"] = value
            elif key == "port":
                with contextlib.suppress(ValueError):
                    parsed["port"] = int(value)
            elif key == "proxyjump":
                parsed["proxyjump"] = None if value.lower() == "none" else value
            elif key == "identityagent":
                parsed["identityagent"] = None if value.lower() == "none" else value
        logger.debug(
            "resolved %s: hostname=%s port=%s",
            alias,
            parsed.get("hostname"),
            parsed.get("port"),
        )
        return parsed

    def check_ssh_agent(self) -> dict:
        """Check if ``ssh-agent`` is available and has identities.

        Returns ``{"available": bool, "has_identities": bool}``.
        Key material and fingerprints are never logged or returned.
        """
        logger.debug("checking ssh-agent availability")
        try:
            result = self._run(("ssh-add", "-l"), timeout=_KEYGEN_TIMEOUT)
        except OSError:
            logger.debug("ssh-add not available")
            return {"available": False, "has_identities": False}
        except subprocess.TimeoutExpired:
            logger.debug("ssh-add timed out")
            return {"available": False, "has_identities": False}
        # ssh-add -l exit codes:
        #   0 = agent running, identities present
        #   1 = agent running, no identities
        #   2 = cannot connect to agent
        if result.returncode == 0:
            logger.debug("ssh-agent available with identities")
            return {"available": True, "has_identities": True}
        if result.returncode == 1:
            logger.debug("ssh-agent available without identities")
            return {"available": True, "has_identities": False}
        logger.debug("ssh-agent not available (exit %d)", result.returncode)
        return {"available": False, "has_identities": False}

    def run_remote(
        self,
        host_alias: str,
        command: str,
        *,
        timeout: float,
    ) -> ProcessResult:
        """Execute a fixed *command* on a remote host via SSH.

        The *command* must be a fixed string generated by system code, not
        user input.  Uses ``BatchMode=yes`` to prevent password prompts.
        """
        alias = SafeHostAlias(host_alias)
        connect_timeout = max(1, int(timeout))
        identity_args = self._identity_args()
        argv: list[str] = [
            "ssh",
            "-o", "BatchMode=yes",
            "-o", f"ConnectTimeout={connect_timeout}",
            *identity_args,
            str(alias),
            command,
        ]
        logger.debug("executing remote command on %s", alias)
        try:
            return self._run(argv, timeout=timeout)
        except subprocess.TimeoutExpired:
            logger.debug("remote command on %s timed out", alias)
            return ProcessResult(returncode=124, stdout="", stderr="timeout")
        except OSError as error:
            logger.debug("remote command on %s could not start: %s", alias, error)
            return ProcessResult(returncode=127, stdout="", stderr=str(error))

    def get_host_key_status(self, host_alias: str) -> KnownHostStatus:
        """Check whether the host key for *host_alias* is in known_hosts.

        Returns :attr:`KnownHostStatus.KNOWN` if the key is present,
        otherwise :attr:`KnownHostStatus.UNKNOWN`.
        """
        alias = SafeHostAlias(host_alias)
        try:
            result = self._run(
                ("ssh-keygen", "-F", str(alias)),
                timeout=_KEYGEN_TIMEOUT,
            )
        except OSError:
            logger.debug("ssh-keygen not available")
            return KnownHostStatus.UNKNOWN
        except subprocess.TimeoutExpired:
            logger.debug("ssh-keygen -F timed out for %s", alias)
            return KnownHostStatus.UNKNOWN
        if result.returncode == 0 and result.stdout.strip():
            return KnownHostStatus.KNOWN
        return KnownHostStatus.UNKNOWN

    def get_host_fingerprint(self, host_alias: str) -> str | None:
        """Return the SHA256 fingerprint of a host's key.

        Uses ``ssh-keyscan`` to fetch the key, then ``ssh-keygen -lf -`` to
        compute the fingerprint.  Returns ``None`` if the host is unreachable
        or the fingerprint cannot be determined.
        """
        alias = SafeHostAlias(host_alias)
        try:
            keyscan = self._run(
                ("ssh-keyscan", "-T", "10", str(alias)),
                timeout=_KEYSCAN_TIMEOUT,
            )
        except OSError:
            logger.debug("ssh-keyscan not available")
            return None
        except subprocess.TimeoutExpired:
            logger.debug("ssh-keyscan timed out for %s", alias)
            return None
        if not keyscan.stdout.strip():
            logger.debug("ssh-keyscan returned no keys for %s", alias)
            return None
        try:
            fingerprint = self._run(
                ("ssh-keygen", "-lf", "-"),
                timeout=_KEYGEN_TIMEOUT,
                input_text=keyscan.stdout,
            )
        except OSError:
            logger.debug("ssh-keygen not available")
            return None
        except subprocess.TimeoutExpired:
            logger.debug("ssh-keygen -lf timed out")
            return None
        if fingerprint.returncode != 0:
            return None
        for line in fingerprint.stdout.splitlines():
            parts = line.split()
            if len(parts) >= 2 and parts[1].startswith("SHA256:"):
                return parts[1]
        return None

    def confirm_host_key(self, host_alias: str) -> bool:
        """Add a host's key to known_hosts via ``ssh-keyscan -H``.

        The hostname is hashed (``-H``) for privacy.  Returns ``True`` if
        the key was successfully appended.
        """
        alias = SafeHostAlias(host_alias)
        try:
            result = self._run(
                ("ssh-keyscan", "-H", "-T", "10", str(alias)),
                timeout=_KEYSCAN_TIMEOUT,
            )
        except OSError:
            logger.debug("ssh-keyscan not available")
            return False
        except subprocess.TimeoutExpired:
            logger.debug("ssh-keyscan timed out for %s", alias)
            return False
        if result.returncode != 0 or not result.stdout.strip():
            logger.debug("ssh-keyscan returned no keys for %s", alias)
            return False
        try:
            self._known_hosts_file.parent.mkdir(parents=True, exist_ok=True)
            with open(self._known_hosts_file, "a", encoding="utf-8") as handle:
                handle.write(result.stdout)
                if not result.stdout.endswith("\n"):
                    handle.write("\n")
        except OSError as error:
            logger.warning("failed to write known_hosts: %s", error)
            return False
        logger.debug("confirmed host key for %s", alias)
        return True

    def test_authentication(
        self,
        host_alias: str,
        *,
        timeout: float,
    ) -> bool:
        """Test SSH authentication using ``BatchMode=yes``.

        Returns ``True`` if authentication succeeds without a password
        prompt.  The host key must already be in known_hosts.
        """
        alias = SafeHostAlias(host_alias)
        connect_timeout = max(1, int(timeout))
        identity_args = self._identity_args()
        argv: list[str] = [
            "ssh",
            "-o", "BatchMode=yes",
            "-o", f"ConnectTimeout={connect_timeout}",
            "-o", "StrictHostKeyChecking=yes",
            *identity_args,
            str(alias),
            "true",
        ]
        logger.debug("testing authentication for %s", alias)
        try:
            result = self._run(argv, timeout=timeout)
        except OSError:
            logger.debug("ssh could not start for %s", alias)
            return False
        except subprocess.TimeoutExpired:
            logger.debug("ssh timed out for %s", alias)
            return False
        if result.returncode == 0:
            logger.debug("authentication succeeded for %s", alias)
            return True
        logger.debug("authentication failed for %s (exit %d)", alias, result.returncode)
        return False

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _detect_identity_files(self) -> list[str]:
        """Detect SSH private key files in ``~/.ssh/``.

        SSH automatically tries standard key names (``id_rsa``,
        ``id_ed25519``, etc.).  When ``-i`` is used, SSH *replaces* its
        default list, so we must include standard names explicitly.

        Scans for:
        * Standard names: ``id_rsa``, ``id_ecdsa``, ``id_ed25519``,
          ``id_xmss``, ``id_dsa``, ``identity``
        * Non-standard names ending in ``_rsa``, ``_ed25519``,
          ``_ecdsa``, ``_dsa`` (e.g. ``fluid_scientist_ed25519``)

        Returns a list of absolute path strings (capped at
        :data:`_MAX_IDENTITY_FILES`).  No paths are logged.
        """
        ssh_dir = self._known_hosts_file.parent
        if not ssh_dir.is_dir():
            return []
        identities: list[str] = []
        try:
            entries = sorted(ssh_dir.iterdir())
        except OSError:
            return []
        for entry in entries:
            name = entry.name
            # Exclude public keys, scripts, and config files.
            if name.endswith(_SSH_DIR_EXCLUDE_SUFFIXES):
                continue
            if name in _SSH_DIR_EXCLUDES:
                continue
            # Match standard names or non-standard key suffixes.
            is_standard = name in _STANDARD_KEY_NAMES
            has_key_suffix = any(name.endswith(s) for s in _KEY_SUFFIXES)
            if not (is_standard or has_key_suffix):
                continue
            # Must be a regular file.
            if not entry.is_file():
                continue
            identities.append(str(entry))
            if len(identities) >= _MAX_IDENTITY_FILES:
                break
        return identities

    def _identity_args(self) -> tuple[str, ...]:
        """Return ``-i <path>`` argument pairs for all detected key files."""
        identities = self._detect_identity_files()
        args: list[str] = []
        for identity in identities:
            args.extend(["-i", identity])
        return tuple(args)

    def _run(
        self,
        argv: tuple[str, ...],
        *,
        timeout: float,
        input_text: str | None = None,
    ) -> ProcessResult:
        """Execute *argv* via the runner and truncate output."""
        result = self._runner.run(argv, timeout=timeout, input_text=input_text)
        return ProcessResult(
            result.returncode,
            self._truncate(result.stdout),
            self._truncate(result.stderr),
        )

    def _truncate(self, text: str) -> str:
        if len(text) <= self._max_output_chars:
            return text
        return text[: self._max_output_chars]
